$INF = 'INF'
$WRN = 'WRN'
$ERR = 'ERR'

$REQUIRES_ELEVATION = if (-not $IS_ELEVATED) { ' *' }

$FORM_WIDTH = 670
$FORM_HEIGHT = 625

$BTN_WIDTH = 167
$BTN_HEIGHT = 28

$CBOX_WIDTH = 145
$CBOX_HEIGHT = 20
$CBOX_SIZE = "$CBOX_WIDTH, $CBOX_HEIGHT"

$INT_SHORT = 5
$INT_NORMAL = 15
$INT_LONG = 30
$INT_TAB_ADJ = 4
$INT_GROUP_TOP = 20

$INT_BTN_SHORT = $BTN_HEIGHT + $INT_SHORT
$INT_BTN_NORMAL = $BTN_HEIGHT + $INT_NORMAL
$INT_BTN_LONG = $BTN_HEIGHT + $INT_LONG

$INT_CBOX_SHORT = $CBOX_HEIGHT + $INT_SHORT
$INT_CBOX_NORMAL = $CBOX_HEIGHT + $INT_NORMAL

$GRP_WIDTH = $INT_NORMAL + $BTN_WIDTH + $INT_NORMAL

$BTN_INIT_LOCATION = "$INT_NORMAL, $INT_GROUP_TOP"
$GRP_INIT_LOCATION = "$INT_NORMAL, $INT_NORMAL"

$SHIFT_BTN_SHORT = "0, $INT_BTN_SHORT"
$SHIFT_BTN_NORMAL = "0, $INT_BTN_NORMAL"
$SHIFT_BTN_LONG = "0, $INT_BTN_LONG"

$SHIFT_CBOX_SHORT = "0, $INT_CBOX_SHORT"
$SHIFT_CBOX_NORMAL = "0, $INT_CBOX_NORMAL"
$SHIFT_CBOX_EXECUTE = "$($INT_LONG - $INT_SHORT), $($INT_BTN_SHORT - $INT_SHORT)"

$SHIFT_GRP_HOR_NORMAL = "$($GRP_WIDTH + $INT_NORMAL), 0"

$SHIFT_LBL_BROWSER = "$INT_LONG, $($INT_BTN_SHORT - $INT_SHORT)"

$FONT_NAME = 'Microsoft Sans Serif'
$BTN_FONT = "$FONT_NAME, 10"

$TXT_START_AFTER_DOWNLOAD = 'Start after download'
$TXT_OPENS_IN_BROWSER = 'Opens in the browser'
$TXT_AV_WARNING = "This file may trigger anti-virus false positive!`nIt is recommended to disable anti-virus software for download and subsequent use of this file!"

$TIP_START_AFTER_DOWNLOAD = "Execute after download has finished`nIf download is a ZIP file, it will get extracted first"
