$FONT_NAME = 'Microsoft Sans Serif'
$BTN_FONT = "$FONT_NAME, 10"

$FORM_HEIGHT = 645
$FORM_WIDTH = 665

$INT_SHORT = 5
$INT_NORMAL = 15
$INT_LONG = 40
$INT_TAB_ADJ = 4
$INT_GROUP_TOP = 20

$BTN_HEIGHT = 28
$BTN_WIDTH_NORMAL = 166
$BTN_INT_SHORT = $BTN_HEIGHT + $INT_SHORT
$BTN_INT_NORMAL = $BTN_HEIGHT + $INT_NORMAL
$BTN_SHIFT_HOR_SHORT = "$BTN_INT_SHORT, 0"
$BTN_SHIFT_HOR_NORMAL = "$BTN_INT_NORMAL, 0"
$BTN_SHIFT_VER_SHORT = "0, $BTN_INT_SHORT"
$BTN_SHIFT_VER_NORMAL = "0, $BTN_INT_NORMAL"

$CBOX_HEIGHT = 20
$CBOX_INT_SHORT = $CBOX_HEIGHT + $INT_SHORT
$CBOX_INT_NORMAL = $CBOX_HEIGHT + $INT_NORMAL
$CBOX_SHIFT_HOR_SHORT = "$CBOX_INT_SHORT, 0"
$CBOX_SHIFT_HOR_NORMAL = "$CBOX_INT_NORMAL, 0"
$CBOX_SHIFT_VER_SHORT = "0, $CBOX_INT_SHORT"
$CBOX_SHIFT_VER_NORMAL = "0, $CBOX_INT_NORMAL"

$INF = 'INF'
$WRN = 'WRN'
$ERR = 'ERR'

$REQUIRES_ELEVATION = if (-not $IS_ELEVATED) {' *'}
