$_FORM_FONT_TYPE = 'Microsoft Sans Serif'
$_BUTTON_FONT = "$_FORM_FONT_TYPE, 10"

$_FORM_HEIGHT = 620
$_FORM_WIDTH = 650

$_INTERVAL_SHORT = 5
$_INTERVAL_NORMAL = 15
$_INTERVAL_LONG = 40
$_INTERVAL_TAB_ADJUSTMENT = 4
$_INTERVAL_GROUP_TOP = 20

$_BUTTON_HEIGHT = 28
$_BUTTON_WIDTH_NORMAL = 160
$_BUTTON_INTERVAL_SHORT = $_BUTTON_HEIGHT + $_INTERVAL_SHORT
$_BUTTON_INTERVAL_NORMAL = $_BUTTON_HEIGHT + $_INTERVAL_NORMAL
$_BUTTON_SHIFT_VERTICAL_SHORT = "0, $_BUTTON_INTERVAL_SHORT"
$_BUTTON_SHIFT_HORIZONTAL_SHORT = "$_BUTTON_INTERVAL_SHORT, 0"
$_BUTTON_SHIFT_VERTICAL_NORMAL = "0, $_BUTTON_INTERVAL_NORMAL"
$_BUTTON_SHIFT_HORIZONTAL_NORMAL = "$_BUTTON_INTERVAL_NORMAL, 0"

$_CHECK_BOX_HEIGHT = 20
$_CHECK_BOX_INTERVAL_SHORT = $_CHECK_BOX_HEIGHT + $_INTERVAL_SHORT
$_CHECK_BOX_INTERVAL_NORMAL = $_CHECK_BOX_HEIGHT + $_INTERVAL_NORMAL
$_CHECK_BOX_SHIFT_VERTICAL_SHORT = "0, $_CHECK_BOX_INTERVAL_SHORT"
$_CHECK_BOX_SHIFT_HORIZONTAL_SHORT = "$_CHECK_BOX_INTERVAL_SHORT, 0"
$_CHECK_BOX_SHIFT_VERTICAL_NORMAL = "0, $_CHECK_BOX_INTERVAL_NORMAL"
$_CHECK_BOX_SHIFT_HORIZONTAL_NORMAL = "$_CHECK_BOX_INTERVAL_NORMAL, 0"
