$_BUTTON_WIDTH_DOWNLOAD = 160
$_CHECK_BOX_SIZE_DOWNLOAD = "$($_BUTTON_WIDTH_DOWNLOAD), $($_CHECK_BOX_HEIGHT)"

$_AV_WARNING_MESSAGE = "!! THIS FILE MAY TRIGGER ANTI-VIRUS FALSE POSITIVE !!`n!! IT IS RECOMMENDED TO DISABLE A/V SOFTWARE FOR DOWNLOAD AND SUBESEQUENT USE OF THIS FILE !!"

$_TAB_DOWNLOADS_INSTALLERS = New-Object System.Windows.Forms.TabPage
$_TAB_DOWNLOADS_INSTALLERS.Text = 'Downloads: Installers'
$_TAB_DOWNLOADS_INSTALLERS.UseVisualStyleBackColor = $True

$_TAB_CONTROL.Controls.AddRange(@($_TAB_DOWNLOADS_INSTALLERS))
