name: Create Release
description: Create a GitHub release with build artifacts

inputs:
  tag:
    description: The tag name to release
    required: true

runs:
  using: composite
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        name: build-output
        path: artifacts

    - name: Create release
      uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ inputs.tag }}
        generate_release_notes: true
        files: |
          artifacts/build/qiiwexc.bat
          artifacts/build/qiiwexc.ps1
          artifacts/build/autounattend-*.xml
