name: Dependabot auto-merge

permissions: {}

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  automerge:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
